version: '3.8'

services:
  feishu-chatops:
    build: .
    container_name: feishu-chatops
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatops-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: feishu-chatops-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - feishu-chatops
    restart: unless-stopped
    networks:
      - chatops-network

  # Redis缓存（可选，用于会话管理）
  redis:
    image: redis:alpine
    container_name: feishu-chatops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - chatops-network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  chatops-network:
    driver: bridge